# This template contains a generic dependabot.yml file with all sorts of ecosystems configured. Note that the NPM ecosystem is not listed. Consult the README.md file of this repository for more information and alternatives.
version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"

  # Maintain dependencies for Composer
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"

  # Maintain dependencies for Terraform
  - package-ecosystem: "terraform"
    directory: "terraform/"
    schedule:
      interval: "monthly"

  # Maintain dependencies for Gradle
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"

  # Maintain dependencies for NuGet
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
