name: CLI
on:
  workflow_dispatch:
  push:
    tags:
      - v*
  pull_request:
    branches:
      - main
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - run: echo "🤖  Testing"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test