name: CLI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    tags:
      - v*

permissions:
  id-token: write
  contents: write
  pull-requests: read

defaults:
  run:
    working-directory: cli/

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Link and prepare generator
        run: cd ../generator && yarn && yarn build && yarn link && cd ../cli && yarn link @recognizebv/sc3000-generator
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test

  create-release:
    runs-on: ubuntu-latest
    name: Create release
    needs: [test]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Link and prepare generator
        run: cd ../generator && yarn && yarn build && yarn link && cd ../cli && yarn link @recognizebv/sc3000-generator
      - name: Install dependencies
        run: yarn
      - name: Write release version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Change version
        uses: reedyuk/npm-version@1.2.1
        with:
          version: ${{ env.VERSION }}
      - name: Build
        run: yarn build
      - name: Pack
        run: npx oclif pack tarballs
      - uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ contains(github.ref, '-beta') }}
          generate_release_notes: true
          files: |
            cli/dist/*.tar.gz
            cli/dist/*.tar.xz
