name: "Code Scanning"

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  code-scanning-javascript:
    name: Perform code scanning (JavaScript)
    uses: recognizegroup/security/.github/workflows/code-scanning-javascript.yaml@v2
