name: Infrastructure
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  determine-environment:
    runs-on: ubuntu-latest
    name: Determine environment
    steps:
      - run: echo "🤖  Finding correct environment"
    outputs:
      environment: ${{ github.ref == 'refs/heads/main' && 'prd' || (startsWith(github.ref, 'refs/heads/release/') && 'acc' || 'tst') }}

  build-registry-docker-image:
    runs-on: ubuntu-latest
    name: Build registry Docker image
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: recognizegroup.azurecr.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: recognizegroup.azurecr.io/recognize/super-cheetah-3000/registry:${{ github.sha }}
          context: registry/
          file: registry/Dockerfile
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

  infrastructure:
    needs: [determine-environment, build-registry-docker-image]
    name: Deploy infrastructure
    defaults:
      run:
        working-directory: terraform/
    runs-on: ubuntu-latest
    environment: ${{ needs.determine-environment.outputs.environment }}
    concurrency: infrastructure-${{ needs.determine-environment.outputs.environment }}
    outputs:
      url: ${{ steps.terragrunt.outputs.url }}
    env:
      ENVIRONMENT: ${{ needs.determine-environment.outputs.environment }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false
    - name: Setup Terragrunt
      uses: autero1/action-terragrunt@v1.3.2
      with:
        terragrunt_version: latest
    - name: Terragrunt Apply
      id: terragrunt
      run: terragrunt run-all apply --terragrunt-non-interactive
      env:
        ARM_USE_OIDC: true
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        REGISTRY_AUTH_CLIENT_SECRET: ${{ secrets.REGISTRY_AUTH_CLIENT_SECRET }}
        ARM_SKIP_PROVIDER_REGISTRATION: true
        DOCKER_IMAGE_REGISTRY: recognizegroup.azurecr.io/recognize/super-cheetah-3000/registry
        DOCKER_IMAGE_TAG_REGISTRY: ${{ github.sha }}
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
