name: Publish generator
on:
  workflow_call:
    inputs:
      directory:
        description: 'Directory where the generator is located'
        type: string
        required: false
        default: ''
      registry_azure_client_id:
        description: 'Azure client ID for the registry'
        type: string
        required: true
      registry_azure_tenant_id:
        description: 'Azure tenant ID for the registry'
        type: string
        required: true
      registry_location:
        description: 'Location of the registry'
        type: string
        default: 'sc3000.recognize.nl'
      version:
        description: 'Version to publish'
        type: string
        required: true
    secrets:
      registry_azure_client_secret:
        description: 'Azure client secret for the registry'
        required: true

jobs:
  publish-generator:
    runs-on: ubuntu-latest
    name: Publish generator
    defaults:
        run:
          working-directory: ${{ inputs.directory }}
    env:
      TAG: ${{ inputs.version }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Request access token for Azure AD
        id: azure_login
        uses: Azure/azure-resource-login-action@v1.0.0
        with:
          resource-url: ${{ inputs.registry_azure_client_id }}/.default
          creds: |-
            {
                "clientId": "${{ inputs.registry_azure_client_id }}",
                "clientSecret": "${{ secrets.registry_azure_client_secret }}",
                "subscriptionId": "00000000-0000-0000-0000-000000000000",
                "tenantId": "${{ inputs.registry_azure_tenant_id }}"
            }
      - name: Login to registry
        run: echo "//${{ inputs.registry_locaiton }}/:_authToken=$NODE_AUTH_TOKEN" >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ steps.azure_login.outputs.token }}
      - name: Change version to ${{ github.ref_name }}
        run: yarn version --new-version ${TAG#v} --no-git-tag-version
      - name: Publish
        run: yarn publish --access public --registry https://${{ inputs.registry_location }}
